# Generated by Django 4.1.6 on 2023-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_students_email_alter_students_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='encoding',
            field=models.BinaryField(null=True),
        ),
    ]
