# Generated by Django 4.1.6 on 2023-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_students_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
